# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.1.0

recipe:
  name: jupyterhub-traefik-proxy
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterhub-traefik-proxy/jupyterhub_traefik_proxy-${{ version }}.tar.gz
  sha256: b9ba2c4f120f9fc9c4ce6dc8340f216876ca94b00d3a74fb8213377edf0222f0
  patches:
    - 000-ipv4-localhost.diff

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: jupyterhub-traefik-proxy
    build:
      noarch: python
      script:
        - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
    requirements:
      host:
        - pip
        - python ${{ python_min }}.*
      run:
        - aiohttp
        - bcrypt
        - escapism
        - jupyterhub >=0.9
        - python >=${{ python_min }}
        - toml
        - traefik >=2,<4
    tests:
      - python:
          imports: jupyterhub_traefik_proxy.fileprovider
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - 3.13.*

  - package:
      name: jupyterhub-traefik-proxy-with-consul
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterhub-traefik-proxy", upper_bound="x.x.x") }}
        - python-consul2
    tests:
      - python:
          imports: jupyterhub_traefik_proxy.consul
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - 3.13.*

  - package:
      name: jupyterhub-traefik-proxy-with-etcd
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterhub-traefik-proxy", upper_bound="x.x.x") }}
        - etcdpy
    tests:
      - python:
          imports: jupyterhub_traefik_proxy.etcd
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - 3.13.*

  - package:
      name: jupyterhub-traefik-proxy-with-redis
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterhub-traefik-proxy", upper_bound="x.x.x") }}
        - redis-py
    tests:
      - python:
          imports: jupyterhub_traefik_proxy.redis
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - 3.13.*

  - package:
      name: jupyterhub-traefik-proxy-with-yaml
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterhub-traefik-proxy", upper_bound="x.x.x") }}
        - ruamel.yaml
    tests:
      - python:
          imports: jupyterhub_traefik_proxy
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - 3.13.*

  - package:
      name: jupyterhub-traefik-proxy-with-all
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("jupyterhub-traefik-proxy-with-consul", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("jupyterhub-traefik-proxy-with-etcd", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("jupyterhub-traefik-proxy-with-redis", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("jupyterhub-traefik-proxy-with-yaml", upper_bound="x.x.x") }}
        - ${{ pin_subpackage("jupyterhub-traefik-proxy", upper_bound="x.x.x") }}
    tests:
      - python:
          imports: jupyterhub_traefik_proxy
          pip_check: true
          python_version:
            - ${{ python_min }}.*
            - 3.13.*
      - files:
          recipe:
            - run_test_all.py
          source:
            - tests/
        requirements:
          run:
            - certipy
            - notebook >=4.0
            - pip
            - pytest
            - pytest-asyncio >=0.17,<0.23
            - pytest-cov
            - pytest-timeout
            - redis-server
            - urllib3 <2
            - websockets
        script:
          - python run_test_all.py

about:
  summary: JupyterHub proxy implementation with traefik
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://jupyterhub-traefik-proxy.readthedocs.io
  repository: https://github.com/jupyterhub/traefik-proxy

extra:
  feedstock-name: jupyterhub-traefik-proxy
  recipe-maintainers:
    - bollwyvl
